export const mockEstructura = [
  {
    id: 116,
    denominacion: "DPT DE PINAR DEL RIO",
    abreviatura: "",
    forma_organizativa: "9837",
    DPA: "9054",
    actividad_economica: "9997",
    children: [
      {
        id: 141,
        codigo: "2110",
        denominacion: "DMT SAN JUAN Y MARTINEZ",
        forma_organizativa: "9837",
        DPA: "10133",
        children: [],
      },
      {
        id: 140,
        codigo: "2109",
        denominacion: "DMT SAN LUIS",
        forma_organizativa: "9837",
        DPA: "9825",
        children: [],
      },
      {
        id: 135,
        codigo: "2104",
        denominacion: "DMT VIÑALES",
        forma_organizativa: "9837",
        DPA: "9820",
        children: [],
      },
      {
        id: 134,
        codigo: "2103",
        denominacion: "DMT MINAS DE MATAHAMBRE",
        forma_organizativa: "9837",
        DPA: "9819",
        children: [
          {
            id: 164,
            codigo: "2103.5",
            denominacion: "Cabeza",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
          {
            id: 163,
            codigo: "2103.4",
            denominacion: "Pons",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
          {
            id: 162,
            codigo: "2103.3",
            denominacion: "Minas  ",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
          {
            id: 161,
            codigo: "2103.2",
            denominacion: "La Sabana",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
          {
            id: 160,
            codigo: "2103.1",
            denominacion: "Santa Lucía",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
          {
            id: 166,
            codigo: "2103.7",
            denominacion: "San Carlos",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
          {
            id: 165,
            codigo: "2103.6",
            denominacion: "Sumidero",
            forma_organizativa: "9884",
            DPA: "9819",
            children: [],
          },
        ],
      },
      {
        id: 142,
        codigo: "2111",
        denominacion: "DMT GUANE",
        forma_organizativa: "9837",
        DPA: "9826",
        children: [],
      },
      {
        id: 139,
        codigo: "2108",
        denominacion: "DMT PINAR DEL RIO",
        forma_organizativa: "9837",
        DPA: "9824",
        children: [],
      },
      {
        id: 138,
        codigo: "2107",
        denominacion: "DMT CONSOLACION DEL SUR",
        forma_organizativa: "9837",
        DPA: "9823",
        children: [],
      },
      {
        id: 137,
        codigo: "2106",
        denominacion: "DMT LOS PALACIOS",
        forma_organizativa: "9837",
        DPA: "9822",
        children: [],
      },
      {
        id: 136,
        codigo: "2105",
        denominacion: "DMT LA PALMA",
        forma_organizativa: "9837",
        DPA: "9821",
        children: [],
      },
      {
        id: 133,
        codigo: "2102",
        denominacion: "DMT MANTUA",
        forma_organizativa: "9837",
        DPA: "9818",
        children: [
          {
            id: 159,
            codigo: "2102.9",
            denominacion: "Mantua",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 158,
            codigo: "2102.8",
            denominacion: "Macurije",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 157,
            codigo: "2102.7",
            denominacion: "Dimas",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 156,
            codigo: "2102.6",
            denominacion: "La Ceja",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 155,
            codigo: "2102.5",
            denominacion: "El Roble",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 154,
            codigo: "2102.4",
            denominacion: "Arroyos",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 153,
            codigo: "2102.3",
            denominacion: "Km8",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 151,
            codigo: "2102.1",
            denominacion: "KM.21",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
          {
            id: 152,
            codigo: "2102.2",
            denominacion: "Montezuelo",
            forma_organizativa: "9884",
            DPA: "9818",
            children: [],
          },
        ],
      },
      {
        id: 132,
        codigo: "2101",
        denominacion: "DMT SANDINO",
        forma_organizativa: "9837",
        DPA: "9817",
        children: [
          {
            id: 150,
            codigo: "2101.8",
            denominacion: "Manuel Lazo",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 149,
            codigo: "2101.7",
            denominacion: "Las Martinas",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 148,
            codigo: "2101.6",
            denominacion: "Cortés",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 147,
            codigo: "2101.5",
            denominacion: "Bolivar ",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 146,
            codigo: "2101.4",
            denominacion: "Martí",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 145,
            codigo: "2101.3",
            denominacion: "Pasada de Marín",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 144,
            codigo: "2101.2",
            denominacion: "Guanahacabibes               ",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
          {
            id: 143,
            codigo: "2101.1",
            denominacion: "Sandino",
            forma_organizativa: "9884",
            DPA: "9817",
            children: [],
          },
        ],
      },
    ],
  },
];
